# Working with parquet files

## Objective

+ In this assignment, we will use the data downloaded with the module `data_manager` to create features.

(11 pts total)

## Prerequisites

+ This notebook assumes that price data is available to you in the environment variable `PRICE_DATA`. If you have not done so, then execute the notebook `01_materials/labs/2_data_engineering.ipynb` to create this data set.

+ Load the environment variables using dotenv. (1 pt)

In [24]:
%load_ext dotenv
%dotenv

The dotenv extension is already loaded. To reload it, use:
  %reload_ext dotenv

In [25]:
import dask.dataframe as dd

+ Load the environment variable `PRICE_DATA`.
+ Use [glob](https://docs.python.org/3/library/glob.html) to find the path of all parquet files in the directory `PRICE_DATA`.

(1pt)

In [26]:
import os
from glob import glob

# Write your code below.
PRICE_DATA = os.getenv('PRICE_DATA')

For each ticker and using Dask, do the following:

+ Add lags for variables Close and Adj_Close.
+ Add returns based on Close:
    
    - `returns`: (Close / Close_lag_1) - 1

+ Add the following range: 

    - `hi_lo_range`: this is the day's High minus Low.

+ Assign the result to `dd_feat`.

(4 pt)

In [ ]:
# Load parquet files from PRICE_DATA env to create a list of files for input.
parquet_files = glob(os.path.join(PRICE_DATA, "**/*.parquet"), recursive = True)
dd_px = dd.read_parquet(parquet_files).set_index("ticker")

#Add lags for Close 
dd_shift = dd_px.groupby('ticker', group_keys=False).apply(
    lambda x: x.assign(Close_lag_1 = x['Close'].shift(1))
)

#Add returns based on Close
dd_rets = dd_shift.assign(
    Returns = lambda x: x['Close']/x['Close_lag_1'] - 1
)

#Add Lags for Adj Close 
dd_shift = dd_px.groupby('ticker', group_keys=False).apply(
    lambda x: x.assign(Adj_Close_lag_1 = x['Adj Close'].shift(1))
)

# Create the hi_lo_range 
hi_lo_range = dd_px['High'] - dd_px['Low']

#Assign hi_lo_range to dd_feat, though could be done in one step. 
dd_feat = dd_rets.assign(
    hi_lo_range = hi_lo_range
)

/var/folders/tp/lvpjcbh14q1d7sxgfpt7k7xc0000gn/T/ipykernel_7575/2565612406.py:6: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  dd_shift = dd_px.groupby('ticker', group_keys=False).apply(
/var/folders/tp/lvpjcbh14q1d7sxgfpt7k7xc0000gn/T/ipykernel_7575/2565612406.py:16: UserWarning: `meta` is not specified, inferred from partial data. Please provide `meta` if the result is unexpected.
  Before: .apply(func)
  After:  .apply(func, meta={'x': 'f8', 'y': 'f8'}) for dataframe result
  or:     .apply(func, meta=('x', 'f8'))            for series result
  dd_shift = dd_px.groupby('ticker', group_keys=False).apply(

In [32]:
dd_rets.compute()

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Returns
ticker,,,,,,,,,,,
A,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300.0,A.csv,1999,NaN,NaN
A,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100.0,A.csv,1999,31.473534,-0.082386
A,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800.0,A.csv,1999,28.880543,0.089783
A,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600.0,A.csv,1999,31.473534,-0.090909
A,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200.0,A.csv,1999,28.612303,0.026563
...,...,...,...,...,...,...,...,...,...,...,...
ZYME,2020-03-26,31.809999,33.480000,30.875000,32.759998,32.759998,584900.0,ZYME.csv,2020,31.680000,0.034091
ZYME,2020-03-27,31.680000,32.790001,31.000000,32.290001,32.290001,292000.0,ZYME.csv,2020,32.759998,-0.014347
ZYME,2020-03-30,32.290001,36.000000,30.607000,35.880001,35.880001,340400.0,ZYME.csv,2020,32.290001,0.111180
ZYME,2020-03-31,35.680000,35.880001,32.000000,35.470001,35.470001,362900.0,ZYME.csv,2020,35.880001,-0.011427
ZYME,2020-04-01,33.980000,34.470001,31.160000,33.779999,33.779999,255300.0,ZYME.csv,2020,35.470001,-0.047646

In [ ]:
dd_feat.compute()

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Returns,hi_lo_range
ticker,,,,,,,,,,,,
A,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300.0,A.csv,1999,NaN,NaN,7.153078
A,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100.0,A.csv,1999,31.473534,-0.082386,2.280043
A,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800.0,A.csv,1999,28.880543,0.089783,2.816525
A,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600.0,A.csv,1999,31.473534,-0.090909,2.592991
A,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200.0,A.csv,1999,28.612303,0.026563,1.385908
...,...,...,...,...,...,...,...,...,...,...,...,...
ZYME,2020-03-26,31.809999,33.480000,30.875000,32.759998,32.759998,584900.0,ZYME.csv,2020,31.680000,0.034091,2.605000
ZYME,2020-03-27,31.680000,32.790001,31.000000,32.290001,32.290001,292000.0,ZYME.csv,2020,32.759998,-0.014347,1.790001
ZYME,2020-03-30,32.290001,36.000000,30.607000,35.880001,35.880001,340400.0,ZYME.csv,2020,32.290001,0.111180,5.393000
ZYME,2020-03-31,35.680000,35.880001,32.000000,35.470001,35.470001,362900.0,ZYME.csv,2020,35.880001,-0.011427,3.880001
ZYME,2020-04-01,33.980000,34.470001,31.160000,33.779999,33.779999,255300.0,ZYME.csv,2020,35.470001,-0.047646,3.310001

+ Convert the Dask data frame to a pandas data frame. 
+ Add a new feature containing the moving average of `returns` using a window of 10 days. There are several ways to solve this task, a simple one uses `.rolling(10).mean()`.

(3 pt)

In [ ]:
# Write your code below.
dd_feat_df = dd_feat.compute()

rolling_avg = dd_feat_df.groupby('ticker')['Returns'].rolling(10).mean().reset_index(level=0, drop=True)
dd_feat_df['returns_ten_day_avg']=rolling_avg

In [41]:
dd_feat_df.head(15)

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Returns,hi_lo_range,returns_ten_day_avg
ticker,,,,,,,,,,,,,
A,1999-11-18,32.546494,35.765381,28.612303,31.473534,27.068665,62546300.0,A.csv,1999,NaN,NaN,7.153078,NaN
A,1999-11-19,30.713520,30.758226,28.478184,28.880543,24.838577,15234100.0,A.csv,1999,31.473534,-0.082386,2.280043,NaN
A,1999-11-22,29.551144,31.473534,28.657009,31.473534,27.068665,6577800.0,A.csv,1999,28.880543,0.089783,2.816525,NaN
A,1999-11-23,30.400572,31.205294,28.612303,28.612303,24.607880,5975600.0,A.csv,1999,31.473534,-0.090909,2.592991,NaN
A,1999-11-24,28.701717,29.998211,28.612303,29.372318,25.261524,4843200.0,A.csv,1999,28.612303,0.026563,1.385908,NaN
A,1999-11-26,29.238197,29.685265,29.148785,29.461731,25.338428,1729400.0,A.csv,1999,29.372318,0.003044,0.536480,NaN
A,1999-11-29,29.327610,30.355865,29.014664,30.132332,25.915169,4074700.0,A.csv,1999,29.461731,0.022762,1.341202,NaN
A,1999-11-30,30.042919,30.713520,29.282904,30.177038,25.953619,4310000.0,A.csv,1999,30.132332,0.001484,1.430616,NaN
A,1999-12-01,30.177038,31.071173,29.953505,30.713520,26.415012,2957300.0,A.csv,1999,30.177038,0.017778,1.117668,NaN
A,1999-12-02,31.294706,32.188843,30.892345,31.562946,27.145563,3069800.0,A.csv,1999,30.713520,0.027656,1.296497,NaN
A,1999-12-03,32.144135,32.680614,31.697067,31.831188,27.376266,3041600.0,A.csv,1999,31.562946,0.008499,0.983547,0.002427
A,1999-12-06,32.367668,33.217094,32.322960,32.725323,28.145258,2250700.0,A.csv,1999,31.831188,0.028090,0.894135,0.013475
A,1999-12-07,32.725323,32.904148,31.697067,32.367668,27.837664,2215900.0,A.csv,1999,32.725323,-0.010929,1.207081,0.003404
A,1999-12-08,32.367668,32.635910,32.054722,32.322960,27.799208,1887800.0,A.csv,1999,32.367668,-0.001381,0.581188,0.012356
A,1999-12-09,32.367668,32.859444,32.367668,32.770027,28.183710,2029000.0,A.csv,1999,32.322960,0.013831,0.491776,0.011083

Please comment:

+ Was it necessary to convert to pandas to calculate the moving average return?
+ Would it have been better to do it in Dask? Why?

(1 pt)

No, it was not necessary to convert to pandas (Dask also has a rolling.mean() operation); however, given the size of the data, this is better to have been conducted in a pandas dataframe instead of through dask to preserve resources in case of a large amount of memory required to store the dask dataframe and calculate all the rolling averages.

## Criteria

The [rubric](./assignment_1_rubric_clean.xlsx) contains the criteria for grading.

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `HH:MM AM/PM - DD/MM/YYYY`
* The branch name for your repo should be: `assignment-1`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_1.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/production/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at `#cohort-3-help`. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.